"""create bond_instruments

Revision ID: 87a0a44e6940
Revises: 
Create Date: 2026-06-13 23:58:14.616155
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '87a0a44e6940'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bond_instruments',
    sa.Column('instrument_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name_fa', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('isin', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('instrument_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('total_issued', sa.BigInteger(), nullable=True),
    sa.Column('base_volume', sa.BigInteger(), nullable=True),
    sa.Column('market_code', sa.Integer(), nullable=True),
    sa.Column('market_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('segment_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('segment_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('security_type_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('security_type_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('price_ceiling', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('price_floor', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('low_52w', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('high_52w', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('low_yearly', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('high_yearly', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('avg_daily_volume_5y', sa.BigInteger(), nullable=True),
    sa.Column('last_trade_date', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('instrument_code'),
    sa.UniqueConstraint('isin')
    )
    op.create_index('idx_bond_maturity', 'bond_instruments', ['maturity_date'], unique=False)
    op.create_index('idx_bond_status', 'bond_instruments', ['status'], unique=False)
    op.create_index('idx_bond_symbol', 'bond_instruments', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bond_symbol', table_name='bond_instruments')
    op.drop_index('idx_bond_status', table_name='bond_instruments')
    op.drop_index('idx_bond_maturity', table_name='bond_instruments')
    op.drop_table('bond_instruments')
    # ### end Alembic commands ###
